#!/bin/sh -e

selection=$(hacksaw -f "-i %i -g %g")
shotgun $selection - | xclip -t 'image/png' -selection clipboard
xclip -out -selection clipboard >> ~/Pictures/screenshot/$(date '+%Y-%m-%d-%T')-screenshot.png
